In [15]:
import pandas as pd
import numpy as np
print(pd.__version__)
info=np.array(['P','A','N','D','A'])
a=pd.Series(info)
print(a)
x=['anshika','bhatt']
df=pd.DataFrame(x)
print(df)
a=pd.Series(['cat','dog','cow'])
a.map({'cat':'CAT','dog':'DOG'})
a.map('I like {}'.format,na_action='ignore')

1.5.3
0    P
1    A
2    N
3    D
4    A
dtype: object
         0
0  anshika
1    bhatt

0    I like cat
1    I like dog
2    I like cow
dtype: object

In [26]:
import pandas as pd
import matplotlib as mlt
a=pd.Series(['a','b','c'],name="alpha")
a.to_frame()
emp=["khushi","anshika","puja","gurlez"]
id=["1052","1014","1082","1098"]
emp_S=pd.Series(emp)
id_S=pd.Series(id)
frame={'EMP':emp_Series,'ID':id_Series}
result=pd.DataFrame(frame)
print(result)

       EMP    ID
0   khushi  1052
1  anshika  1014
2     puja  1082
3   gurlez  1098

In [28]:
import pandas as pd
info={'ID':['102','104','106'],'department':['btech','mtech'," "]}
df=pd.DataFrame(info)
print(df)
inf=

    ID department
0  102      btech
1  104      mtech
2  106